# Generated by Django 5.0 on 2024-07-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('titleName', models.CharField(max_length=60)),
                ('hasPassport', models.BooleanField()),
                ('salary', models.FloatField()),
                ('birthDate', models.DateField()),
                ('hireDate', models.DateField()),
                ('notes', models.CharField(max_length=300)),
                ('country', models.CharField(choices=[('NIG', 'Nigeria'), ('UK', 'United Kingdom'), ('SA', 'Saudi Arabia'), ('USA', 'United State of America'), ('AUS', 'Australia'), ('RS', 'Russia'), ('AU', 'Austria'), ('GN', 'Ghana'), ('MO', 'Morocco'), ('SD', 'Sudan'), ('SP', 'Spain')], default=None, max_length=60)),
            ],
        ),
    ]
