# Generated by Django 5.0 on 2024-07-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0002_Addingemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phoneNumber',
            field=models.EmailField(default='', max_length=20),
        ),
    ]
