# Generated by Django 5.0 on 2024-07-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0003_AddingephoneNumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phoneNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
