# Generated by Django 5.0 on 2024-07-12 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0005_country_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='country',
        ),
        migrations.AddField(
            model_name='employee',
            name='empCountry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.country'),
        ),
        migrations.AddField(
            model_name='employee',
            name='empDept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.department'),
        ),
    ]
