# Generated by Django 5.0 on 2024-07-12 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0006_remove_employee_country_employee_empcountry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empCountry',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Countrys', to='payrollApp.country'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='empDept',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='Departments', to='payrollApp.department'),
        ),
    ]
