# Generated by Django 5.0 on 2024-07-17 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0008_parttimeemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.country')),
            ],
        ),
        migrations.CreateModel(
            name='OnSiteEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60, null=True)),
                ('last_name', models.CharField(max_length=60, null=True)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.city')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.country')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='payrollApp.state'),
        ),
    ]
