# Generated by Django 5.0 on 2024-07-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0009_city_state_onsiteemployee_city_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
    ]
