# Generated by Django 5.0 on 2024-07-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollApp', '0010_remove_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
